#include <stdio.h>
#include "functions.h"

// Function to get user choice
// @param reads the user choice 
// @return retruns the user choice
char get_user_choice() {
    printf("Enter r (rock), p (paper), s (scissors), or q to quit:\n");
    char choice = read_char();
    return choice;
}

// Function to convert user's choice to a number
// @param choice to get the user's value
// @return returns the value of the condition that is satisfied
int convert_choice(char choice) {
    if (choice == 'r') {
        return 1;
    } else if (choice == 'p') {
        return 2;
    } else if (choice == 's') {
        return 3;
    }
    return 0; 
}

// Function to get the computer's random choice as a number
// @return gives the value of the raandom numbers generated by the computer at the given time.
int get_cpu_choice() {
    return random_int(1, 3);
}

// Function to print the choice made by user or CPU
// @param choice assigns the value chosen to the side the turn of the play i.e computer or user
void print_choice(int choice, int is_user_choice) {
    if (is_user_choice == 1) {
        printf("You chose: ");
    } else {
        printf("CPU chose: ");
    }

    if (choice == 1) printf("Rock\n");
    else if (choice == 2) printf("Paper\n");
    else if (choice == 3) printf("Scissors\n");
}

// Function to determine the winner
// @param takes the values of the user and the computer and compares them 
// @return returns the value or the result when the condition is satisfied
int determine_winner(int user_num, int cpu_num) {
    if (user_num == cpu_num) {
        printf("It's a tie!\n");
        return 0;
    } else if ((user_num == 1 && cpu_num == 3) || 
               (user_num == 2 && cpu_num == 1) || 
               (user_num == 3 && cpu_num == 2)) {
        printf("You won this round!\n");
        return 1;
    } else {
        printf("CPU won this round!\n");
        return -1;
    }
}

int main(void) {
    printf("Welcome to Rock, Paper, Scissors Game!\n");

    int rounds = 0;
    int player_wins = 0;
    int cpu_wins = 0;

    char choice = get_user_choice();

    while (choice != 'q') {
        int user_num = convert_choice(choice);

        if (user_num == 0) {  
            printf("Invalid choice! Please enter 'r', 'p', 's', or 'q' to quit.\n");
            choice = get_user_choice();
            return 0;
        }


        int cpu_num = get_cpu_choice();

        print_choice(user_num, 1); 
        print_choice(cpu_num, 0);  

        // function to declare a winner is called here
        int result = determine_winner(user_num, cpu_num);
        if (result == 1) player_wins++;  // Player wins
        else if (result == -1) cpu_wins++;  // CPU wins

        rounds++;  

        // the current score is updated here
        // with values from the given functions
        printf("Score: You %d - CPU %d (Rounds Played: %d)\n", player_wins, cpu_wins, rounds);

        // Get next user choice
        choice = get_user_choice();
    }

    // When the game ends, thereby required to show the final score
    printf("\nGame Over!\n");
    printf("Final Score: You %d - CPU %d (Total Rounds Played: %d)\n", player_wins, cpu_wins, rounds);

    return 0;
}
